### PR TITLE
Add check pattern v

### PR DESCRIPTION
**Pull request by KSR-Yasuda**
`[v]`.

Doesn't it look like check mark ☑ ?

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Nope, you should follow on the syntax people are familar with. Sepecially this is the same as link syntax in markdown, and adding new markers do have side effects.

**Comment by KSR-Yasuda** [comment]
OK, I got it.

**Comment by KSR-Yasuda** [comment]
But as for Markdown syntax,
link notation was not `[text](URL)` or `[text][LINK_ID]`?

I know sometimes `[text]` is handled as the latter case (i.e. `[text][text]`), though,
if this notation should be cared, isn't it so as the current check pattern `[x]` ?

So, `[x]` is widely known as check mark in ASCII text expression?

**Comment by Mister-Hope** [comment]
See  https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments https://github.com/blog/1825-task-lists-in-all-markdown-documents.

Some of the other git providers are also supporting it.

Since the syntax history is up to 2013, and a lot of people are using them for years, I don't think we need to add a new syntax to support a more "look like" way.

**Comment by KSR-Yasuda** [comment]
OK, thank you.
I got there's some historical background that especially `[x]` has been chosen.

**Pull request closed without merging**
